// <auto-generated />
using System;
using Forge.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forge.Infrastructure.Migrations
{
    [DbContext(typeof(ForgeDbContext))]
    partial class ForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forge.Domain.Entities.AcceptanceCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Satisfied")
                        .HasColumnType("boolean")
                        .HasColumnName("satisfied");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_acceptance_criteria");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_acceptance_criteria_task_id");

                    b.ToTable("acceptance_criteria", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Entities.AgentMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AgentRole")
                        .HasColumnType("integer")
                        .HasColumnName("agent_role");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_agent_memory");

                    b.HasIndex("ProjectId", "AgentRole", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_memory_project_id_agent_role_key");

                    b.ToTable("agent_memory", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Entities.DomainEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("TaskId", "OccurredAt")
                        .HasDatabaseName("ix_events_task_time");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Entities.LlmModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CapabilityTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capability_tier");

                    b.Property<decimal>("CostPerToken")
                        .HasColumnType("numeric(12,8)")
                        .HasColumnName("cost_per_token");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.HasKey("Id")
                        .HasName("pk_models");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Entities.Plugin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_plugins");

                    b.ToTable("plugins", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GitProviderPluginId")
                        .HasColumnType("uuid")
                        .HasColumnName("git_provider_plugin_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_url");

                    b.Property<string>("RootBranch")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("root_branch");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("GitProviderPluginId")
                        .HasDatabaseName("ix_projects_git_provider_plugin_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Entities.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AgentRole")
                        .HasColumnType("integer")
                        .HasColumnName("agent_role");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<decimal>("CostEstimate")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("cost_estimate");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("ModelProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_provider");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_runs");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_runs_task");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Entities.SubTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean")
                        .HasColumnName("done");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_sub_tasks");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_sub_tasks_task_id");

                    b.ToTable("sub_tasks", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BranchName")
                        .HasColumnType("text")
                        .HasColumnName("branch_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorktreeId")
                        .HasColumnType("uuid")
                        .HasColumnName("worktree_id");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("WorktreeId")
                        .IsUnique()
                        .HasDatabaseName("ix_tasks_worktree_id");

                    b.HasIndex("ProjectId", "Priority")
                        .HasDatabaseName("ix_tasks_project_priority");

                    b.HasIndex("ProjectId", "State")
                        .HasDatabaseName("ix_tasks_project_state");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Entities.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_task_id");

                    b.Property<string>("HomeDirectory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_directory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_workers");

                    b.HasIndex("CurrentTaskId")
                        .HasDatabaseName("ix_workers_current_task_id");

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Entities.Worktree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("branch_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_worktrees");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_worktrees_project_id");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasDatabaseName("ux_worktrees_active_task")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("worktrees", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Entities.AcceptanceCriterion", b =>
                {
                    b.HasOne("Forge.Domain.Entities.TaskItem", "Task")
                        .WithMany("AcceptanceCriteria")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acceptance_criteria_tasks_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Domain.Entities.AgentMemory", b =>
                {
                    b.HasOne("Forge.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_memory_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Forge.Domain.Entities.DomainEvent", b =>
                {
                    b.HasOne("Forge.Domain.Entities.TaskItem", "Task")
                        .WithMany("Events")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("fk_events_tasks_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Domain.Entities.Project", b =>
                {
                    b.HasOne("Forge.Domain.Entities.Plugin", "GitProviderPlugin")
                        .WithMany()
                        .HasForeignKey("GitProviderPluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_plugins_git_provider_plugin_id");

                    b.Navigation("GitProviderPlugin");
                });

            modelBuilder.Entity("Forge.Domain.Entities.Run", b =>
                {
                    b.HasOne("Forge.Domain.Entities.TaskItem", "Task")
                        .WithMany("Runs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_runs_tasks_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Domain.Entities.SubTask", b =>
                {
                    b.HasOne("Forge.Domain.Entities.TaskItem", "Task")
                        .WithMany("SubTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sub_tasks_tasks_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Forge.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_projects_project_id");

                    b.HasOne("Forge.Domain.Entities.Worktree", "Worktree")
                        .WithOne()
                        .HasForeignKey("Forge.Domain.Entities.TaskItem", "WorktreeId")
                        .HasConstraintName("fk_tasks_worktrees_worktree_id");

                    b.Navigation("Project");

                    b.Navigation("Worktree");
                });

            modelBuilder.Entity("Forge.Domain.Entities.Worker", b =>
                {
                    b.HasOne("Forge.Domain.Entities.TaskItem", "CurrentTask")
                        .WithMany()
                        .HasForeignKey("CurrentTaskId")
                        .HasConstraintName("fk_workers_tasks_current_task_id");

                    b.Navigation("CurrentTask");
                });

            modelBuilder.Entity("Forge.Domain.Entities.Worktree", b =>
                {
                    b.HasOne("Forge.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worktrees_projects_project_id");

                    b.HasOne("Forge.Domain.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worktrees_tasks_task_id");

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Forge.Domain.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Forge.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("AcceptanceCriteria");

                    b.Navigation("Events");

                    b.Navigation("Runs");

                    b.Navigation("SubTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
